#!/usr/bin/env sh
# shellcheck disable=SC1090,SC1091
# Cross-shell rc file
# sourced by
#  ~/.bash_profile
#  ~/.bashrc
#  ~/.zprofile
#  ~/.zshrc
#  ~/.profile

# SHELLRC_DEBUG=true

# Prevent sourcing more than once per session
if [ "$SHELLRC_SOURCED" ]; then return 0; fi
SHELLRC_SOURCED=true

maybe_echo() {
	[ -z "$SHELLRC_DEBUG" ] && return 0
	[ "$SHELLRC_DEBUG" = true ] && echo "$1"
}

maybe_echo "$HOME/.shellrc"

is_darwin() {
	uname | awk '!/[Dd]arwin/{exit 1}'
}

is_linux() {
	uname | awk '!/[Ll]inux/{exit 1}'
}

is_bash() {
	[ -z "$BASH_VERSION" ] && return 1 || return 0
}

is_zsh() {
	[ -z "$ZSH_VERSION" ] && return 1 || return 0
}

_rename_with_timestamp() {
	maybe_echo "_rename_with_timestamp()"
	TS=$(date -u +"%Y-%m-%dT%H%M%S")
	mv "$1" "$1-$TS" > /dev/null 2>&1
	unset TS
}

_prepend_section_in_file() {
	maybe_echo "_prepend_section_in_file()"
	_SECTION="$1"
	_FILE="$2"
	[ -f "$_FILE" ] || return 1
	_SECTION_READ=$(awk '/BEGIN_SHELLRC/,/END_SHELLRC/{print $0}' "$_FILE")
	if [ -z "$_SECTION_READ" ]; then
		printf '%s\n%s\n' "$_SECTION" "$(cat "$_FILE")" > "$_FILE"
	fi
	unset _SECTION _FILE _SECTION_READ
}

_append_section_in_file() {
	maybe_echo "_append_section_in_file()"
	_SECTION="$1"
	_FILE="$2"
	[ -f "$_FILE" ] || return 1
	_SECTION_READ=$(awk '/BEGIN_SHELLRC/,/END_SHELLRC/{print $0}' "$_FILE")
	if [ -z "$_SECTION_READ" ]; then
		printf '%s\n%s\n' "$(cat "$_FILE")" "$_SECTION" > "$_FILE"
	fi
	unset _SECTION _FILE _SECTION_READ
}

_update_section_in_file() {
	maybe_echo "_update_section_in_file()"
	_SECTION="$1"
	_FILE="$2"
	[ -f "$_FILE" ] || return 1
	# Read current from disk
	_SECTION_READ=$(awk '/BEGIN_SHELLRC/,/END_SHELLRC/{print $0}' "$_FILE")
	# Abort if: no SHELLRC section is found
	if [ -z "$_SECTION_READ" ]; then
		maybe_echo "... $_FILE has no SHELLRC section. Aborting."
		return 0
	# Abort if: SHELLRC section is unchanged
	elif [ "$_SECTION_READ" = "$_SECTION" ]; then
		maybe_echo "... SHELLRC section in $_FILE is unchanged."
		return 0
	# Abort if: destination is newer than .shellrc
	elif [ "$(date -r "$_FILE" "+%s")" -gt "$(date -r "$(_get_shellrc_file)" "+%s")" ]; then
		maybe_echo "... SHELLRC section in $_FILE has recent edits. Aborting."
		return 0
	fi
	maybe_echo "... updating SHELLRC section in $_FILE"
	# Finally replace ssh config section with our section
	_TEMPFILE="$(mktemp)"
	awk '
		BEGIN { sv=ARGV[1]; delete ARGV[1] }
		/BEGIN_SHELLRC/ { print sv; section=1; next }
		/END_SHELLRC/ { section=0; next }
		section {next}
		{print}
	' "$_SECTION" "$_FILE" > "$_TEMPFILE" && mv "$_TEMPFILE" "$_FILE"
	unset _SECTION _SECTION_READ _FILE _TEMPFILE
}

_get_shellrc_file() {
	SHELLRC_FILE=~/.shellrc
	if command -v perl > /dev/null; then
		SHELLRC_FILE=$(perl -MCwd -le 'print Cwd::abs_path(shift)' "$SHELLRC_FILE")
	elif command -v realpath > /dev/null; then
		SHELLRC_FILE=$(realpath "$SHELLRC_FILE")
	else
		SHELLRC_FILE=$(readlink -f "$SHELLRC_FILE")
	fi
	printf "%s" "$SHELLRC_FILE"
	unset SHELLRC_FILE
}

update_shellrc() {
	# https://stackoverflow.com/questions/24118224/how-to-make-asynchronous-function-calls-in-shell-scripts
	F=$(mktemp)
	# utc seconds: date "+%s"
	# file modfied time: date -r <filename> "+%s"
	# Find real .shellrc file if symlinked
	SHELLRC_FILE=$(_get_shellrc_file)
	if ! curl -s -L -o "$F" https://raw.githubusercontent.com/tmslnz/shellrc/main/shellrc; then
		echo "... curl error"
		return 1
	fi
	if ! diff -EBq "$SHELLRC_FILE" "$F" &>/dev/null; then
		echo "... writing $SHELLRC_FILE"
		_rename_with_timestamp "$SHELLRC_FILE"
		cat "$F" > "$SHELLRC_FILE"
		. "$SHELLRC_FILE"
	else
		echo "... no updates available"
	fi
	unset F SHELLRC_FILE
}

setup_sh() {
	is_bash || is_zsh && return 0
	maybe_echo "setup_sh()"
	CONFIGFILE=$HOME/.profile
	{ CONFIG=$(cat) ; } <<-'EOF'
		# BEGIN_SHELLRC
		[ -f ~/.shellrc ] && . ~/.shellrc
		# END_SHELLRC
		EOF
	[ ! -f "$CONFIGFILE" ] && touch "$CONFIGFILE"
	_append_section_in_file "$CONFIG" "$CONFIGFILE"
	_update_section_in_file "$CONFIG" "$CONFIGFILE"
	unset CONFIG CONFIGFILE
}

setup_bash() {
	is_bash || return 0
	maybe_echo "setup_bash()"
	if [ "$BASH_VERSINFO" -lt 4 ]; then
		echo "You are using a very old version of Bash: $BASH_VERSION"
		if is_darwin && command -v brew > /dev/null; then
			echo "Run:"
			echo "$ brew install bash"
			echo "$ enable_homebrew_bash"
		elif is_darwin; then
			echo "$ Please install \"Homebrew\" from https://brew.sh"
			echo "$ enable_homebrew_bash"
		else
			echo "Please update Bash"
		fi
		echo "To silence this message add this to your ~.bashrc"
		echo "export SILENCE_SHELLRC_WARNINGS=true"
	fi
	CONFIGFILE=$HOME/.bash_profile
	{ CONFIG=$(cat) ; } <<-'EOF'
		# BEGIN_SHELLRC
		[ -f /etc/bashrc ] && . /etc/bashrc
		[ -f ~/.shellrc ] && . ~/.shellrc
		# END_SHELLRC
		EOF
	[ ! -f "$CONFIGFILE" ] && touch "$CONFIGFILE"
	_append_section_in_file "$CONFIG" "$CONFIGFILE"
	_update_section_in_file "$CONFIG" "$CONFIGFILE"
	CONFIGFILE=$HOME/.bashrc
	{ CONFIG=$(cat) ; } <<-'EOF'
		# BEGIN_SHELLRC
		[ -f /etc/bashrc ] && . /etc/bashrc
		SHELLRC_DEBUG=false
		[ -f ~/.shellrc ] && . ~/.shellrc
		# END_SHELLRC
		EOF
	[ ! -f "$CONFIGFILE" ] && touch "$CONFIGFILE"
	_append_section_in_file "$CONFIG" "$CONFIGFILE"
	_update_section_in_file "$CONFIG" "$CONFIGFILE"
	unset CONFIG CONFIGFILE
}

enable_homebrew_bash() {
	command -v brew > /dev/null || return 0
	BREW_PREFIX=$(brew --prefix)
	grep -Fxq "$BREW_PREFIX/bin/bash" /etc/shells && return 0
	[ -f "$BREW_PREFIX/bin/bash" ] || return 0
	maybe_echo "enable_homebrew_bash()"
	echo "$BREW_PREFIX/bin/bash" | sudo tee -a /etc/shells
	sudo chsh -s "$BREW_PREFIX/bin/bash"
	cat /etc/shells
	unset BREW_PREFIX
}

disable_homebrew_bash() {
	command -v brew > /dev/null || return 0
	grep -Fxq "$(brew --prefix)/bin/bash" /etc/shells && return 0
	maybe_echo "disable_homebrew_bash()"
	sudo chsh -s /bin/bash
}

setup_zsh() {
	is_zsh || return 0
	maybe_echo "setup_zsh()"
	CONFIGFILE=$HOME/.zshrc
	{ CONFIG=$(cat) ; } <<-'EOF'
		# BEGIN_SHELLRC
		[ -f ~/.shellrc ] && . ~/.shellrc
		# END_SHELLRC
		EOF
	[ ! -f "$CONFIGFILE" ] && touch "$CONFIGFILE"
	_append_section_in_file "$CONFIG" "$CONFIGFILE"
	_update_section_in_file "$CONFIG" "$CONFIGFILE"
	unset CONFIG CONFIGFILE
}

configure_darwin() {
	is_darwin || return 0
	maybe_echo "configure_darwin()"
	export SHELL_SESSIONS_DISABLE=1
	export SHELL_SESSIONS_HISTORY=0
	export BASH_SILENCE_DEPRECATION_WARNING=1
}

configure_linux() {
	is_linux || return 0
	maybe_echo "configure_linux()"
}

set_shell_options() {
	maybe_echo "set_shell_options()"
	[ -f "$HOME/.hushlogin" ] || touch "$HOME/.hushlogin"
}

# shellcheck disable=SC3044
set_bash_options() {
	is_bash || return 0
	maybe_echo "set_bash_options()"
	HISTIGNORE="&:[ ]*:cd ~:~:cd ..:..:clear:history:[bf]g:reboot:shutdown:exit:date:pwd:* --help"
	HISTCONTROL="erasedups:ignorespace"
	HISTSIZE=32768
	HISTFILESIZE=$HISTSIZE
	SAVEHIST=$HISTSIZE
	HISTFILE="${HOME}/.history"
	# Use standard ISO 8601 timestamp
	# %F equivalent to %Y-%m-%d
	# %T equivalent to %H:%M:%S (24-hours format)
	# HISTTIMEFORMAT='%F %T '
	# Prevent file overwrite on stdout redirection
	# Use `>|` to force redirection to an existing file
	# set -o noclobber
	# Update window size after every command
	shopt -s checkwinsize
	# Automatically trim long paths in the prompt (requires Bash 4.x)
	PROMPT_DIRTRIM=2
	# Turn on recursive globbing (enables ** to recurse all directories)
	shopt -s globstar 2> /dev/null
	# Case-insensitive globbing (used in pathname expansion)
	shopt -s nocaseglob;
	# Append to the history file, don't overwrite it
	shopt -s histappend
	# Save multi-line commands as one command
	shopt -s cmdhist
	# Prepend cd to directory names automatically
	shopt -s autocd 2> /dev/null
	# Correct spelling errors during tab-completion
	shopt -s dirspell 2> /dev/null
	# Correct spelling errors in arguments supplied to cd
	shopt -s cdspell 2> /dev/null
	# This defines where cd looks for targets
	# Add the directories you want to have fast access to, separated by colon
	# Ex: CDPATH=".:~:~/projects" will look for targets in the current working directory, in home and in the ~/projects folder
	CDPATH="."
	# This allows you to bookmark your favorite places across the file system
	# Define a variable containing a path and you will be able to cd into it regardless of the directory you're in
	shopt -s cdable_vars
	# Examples:
	# export dotfiles="$HOME/dotfiles"
	# export projects="$HOME/projects"
	# export documents="$HOME/Documents"
	# export dropbox="$HOME/Dropbox"
}

# shellcheck disable=SC2034
set_zsh_options() {
	is_zsh || return 0
	maybe_echo "set_zsh_options()"
	# https://zsh.sourceforge.io/Doc/Release/Options.html
	# setopt extended_history       # record timestamp of command in HISTFILE
	setopt hist_expire_dups_first # delete duplicates first when HISTFILE size exceeds HISTSIZE
	setopt hist_ignore_all_dups
	setopt hist_ignore_space      # ignore commands that start with space
	setopt hist_verify            # show command with history expansion to user before running it
	setopt inc_append_history     # add commands to HISTFILE in order of execution
	# setopt share_history          # share command history data
	setopt hash_list_all
	setopt correct
	# unsetopt extended_history
	HISTORY_IGNORE="(&|[ ]*|cd ~|~|cd ..|..|clear|history|[bf]g|reboot|shutdown|exit|date|pwd|* --help)"
	HISTFILE="${HOME}/.history"
	HISTSIZE=50000
	SAVEHIST=10000
	ZSH_COMPDUMP="$XDG_CACHE_HOME/.zcompdump-$HOST"
}

set_xdg_directories() {
	maybe_echo "set_xdg_directories()"
	if [ -z "$XDG_CONFIG_HOME" ]; then
		mkdir -p "$HOME/.config"
		export XDG_CONFIG_HOME="$HOME/.config"
	fi
	if [ -z "$XDG_CACHE_HOME" ]; then
		mkdir -p "$HOME/.cache"
		export XDG_CACHE_HOME="$HOME/.cache"
	fi
	if [ -z "$XDG_DATA_HOME" ]; then
		mkdir -p "$HOME/.local/share"
		export XDG_DATA_HOME="$HOME/.local/share"
	fi
	if [ -z "$XDG_STATE_HOME" ]; then
		mkdir -p "$HOME/.local/state"
		export XDG_STATE_HOME="$HOME/.local/state"
	fi
	# See https://wiki.archlinux.org/title/XDG_Base_Directory
	# XDG_RUNTIME_DIR
	# XDG_DATA_DIRS
	# XDG_CONFIG_DIRS
}

is_smart_terminal() {
	maybe_echo "is_smart_terminal()"
	case "$TERM" in
		"dumb")
			return 1;;
		xterm*|rxvt*|eterm*|screen*)
			return 0;;
		*)
			return 1;;
	esac
}

set_bash_prompt_string() {
	maybe_echo "set_bash_prompt_string()"
	if ! is_smart_terminal; then
		PS1="> "
		return 0
	fi
	PS1=$'\[\e[1m\]\u\[\e[2m\]@\h\[\e[0;2m\]:\[\e[0m\]\w\[\e[2m\] \xe2\x97\x8f \[\e[0m\]'
}

set_zsh_prompt_string() {
	maybe_echo "set_zsh_prompt_string()"
	if ! is_smart_terminal; then
		PS1="> "
		return 0
	fi
	# shellcheck disable=SC2034
	PROMPT=$'%B%n%{\e[2m%}@%m%{\e[0;2m%}:%{\e[0m%}%~%{\e[2m%} \xe2\x97\x8f %{\e[0m%}'
}

set_ls_colors() {
	maybe_echo "set_ls_colors()"
	# https://geoff.greer.fm/lscolors/
	# Detect which `ls` flavor is in use
	export CLICOLOR=1 # macOS only
	if ls --color > /dev/null 2>&1; then
		LS_COLOR_FLAG="--color"
	else # OS X `ls`
		LS_COLOR_FLAG="-G"
	fi
	# shellcheck disable=SC2139
	alias ls="command ls ${LS_COLOR_FLAG}"
	# export LS_COLORS='no=00:fi=00:di=01;34:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.ogg=01;35:*.mp3=01;35:*.wav=01;35:'
	unset LS_COLOR_FLAG
}

make_aliases() {
	maybe_echo "make_aliases()"
	is_available() {
		command -v "$1" > /dev/null
	}
	if ! type _get_comp_words_by_ref > /dev/null 2>&1; then
		alias sudo='sudo ' # Enable sudo <alias>, only if bash-completion is not loaded.
	fi
	alias lsd="ls -la \${LS_COLOR_FLAG} | grep '^d'" # List only directories
	is_available nano && alias crontab="EDITOR=nano crontab" # Reset EDITOR for crontab
	is_available dscacheutil && alias flushdns="dscacheutil -flushcache && killall -HUP mDNSResponder"
	is_available dig && alias publicip="dig +short myip.opendns.com @resolver1.opendns.com"
	if ! is_available pgrep; then
		# shellcheck disable=SC2317,SC2009
		psgrep () {
			ps aux | grep -Ev grep | grep "$1" | awk '{print $2}'
		}
	fi
	is_available ip && alias localip="ip route get 1 | awk '{print \$NF;exit}'"
	is_available ipconfig && alias localip="ipconfig getifaddr en0"
	alias ips="ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'"
	# macOS fallbacks
	! is_available md5sum && alias md5sum="md5"
	! is_available sha1sum && alias sha1sum="shasum"
	is_darwin && alias dsstore="find . -type f -name '*.DS_Store' -ls -delete"
	# Docker container aliases
	if is_available docker; then
		alias photostructure="docker exec -u photostructure -it photostructure ./photostructure"
	fi
	unset -f is_available
}

configure_nano() {
	command -v nano > /dev/null || return 1
	maybe_echo "configure_nano()"
	if command -v brew > /dev/null && [ -d "$(brew --prefix)/share/nanorc" ]; then
		NANORC_DIR="$(brew --prefix)/share/nanorc"
	elif command -v brew > /dev/null; then
		echo "Run:"
		echo "$ brew install nano nanorc"
	elif [ -d /usr/share/nano ]; then
		NANORC_DIR="/usr/share/nano"
	elif [ -d ~/.nano/nanorc ]; then
		NANORC_DIR=~/.nano/nanorc
	elif [ -d /usr/share/nano-syntax-highlighting ]; then
		NANORC_DIR="/usr/share/nano-syntax-highlighting"
	elif [ -d /etc/nanorc ]; then
		NANORC_DIR="/etc/nanorc"
	fi

	CONFIGFILE=~/.nanorc
	{ CONFIG=$(cat) ; } <<-EOF
		# BEGIN_SHELLRC

		set atblanks        # wrap line at blanks.
		set cutfromcursor   # CTRL+K cuts from cursor position to end of line.
		# set nohelp          # Disable the help information (CTRL+G to view the help screen).
		set softwrap        # Enable softwrap of lines.
		set tabsize 4       # Sets tab-to-spaces size to 4.
		set tabstospaces    # Converts TAB key press to spaces.
		set speller "aspell -x -c"         # Sets what spelling utility to use.
		set constantshow    # Displays useful information e.g. line number and position in the bottom bar.
		set linenumbers     # Lines are numbered.
		set casesensitive   # Case insensitive search.
		set historylog      # Save the last 100 history searches for later use.
		set positionlog     # Saves the cursor position between editing sessions.
		set zap             # Allows you to highlight text (CTRL+SHIFT+ARROW) and delete it with backspace.
		set autoindent      # A new line will have the same number of leading spaces as the previous one.
		set indicator       # Displays a scroll bar on the right that shows the position and size of the current view port.
		set minibar         # Displays file name and other information in the bottom bar. Removes top bar.

		# https://stackoverflow.com/a/74008963
		bind ^Z suspend main

		# Enables the syntax highlighting.
		include "$NANORC_DIR/*.nanorc"

		# END_SHELLRC
		EOF
	[ ! -f "$CONFIGFILE" ] && touch "$CONFIGFILE"
	_append_section_in_file "$CONFIG" "$CONFIGFILE"
	_update_section_in_file "$CONFIG" "$CONFIGFILE"
	unset CONFIG CONFIGFILE NANORC_DIR
}

configure_vim() {
	maybe_echo "configure_vim()"
	VIM_HOME="$XDG_CONFIG_HOME/vim"
	[ -d "$VIM_HOME" ] || (mkdir -p "$VIM_HOME"; mkdir -p "$VIM_HOME/runtime")
	# [ -f "$VIM_HOME/vimrc" ] || touch "$VIM_HOME/vimrc"
	# export VIM="$VIM_HOME"
	# VIMINIT="set viminfo+=n$VIM_HOME/viminfo|:set runtimepath^=$VIM_HOME/runtime|:source $VIM_HOME/vimrc"
	## set runtimepath=~/.config/vim/vimfiles,~/.config/vim,~/.config/vim/vimfiles/after,~/.vim/after
	# export VIMINIT

	CONFIGFILE=$VIM_HOME/vimrc
	{ CONFIG=$(cat) ; } <<-'EOF'
		" BEGIN_SHELLRC

		" https://gist.github.com/simonista/8703722
		" Don't try to be vi compatible
		set nocompatible

		" Helps force plugins to load correctly when it is turned back on below
		filetype off

		" TODO: Load plugins here (pathogen or vundle)

		" Turn on syntax highlighting
		syntax on

		" For plugins to load correctly
		filetype plugin indent on

		" TODO: Pick a leader key
		" let mapleader = ","

		" Security
		set modelines=0

		" Show line numbers
		set number

		" Show file stats
		set ruler

		" Blink cursor on error instead of beeping (grr)
		set visualbell

		" Encoding
		set encoding=utf-8

		" Whitespace
		set wrap
		set textwidth=79
		set formatoptions=tcqrn1
		set tabstop=2
		set shiftwidth=2
		set softtabstop=2
		set expandtab
		set noshiftround

		" Cursor motion
		set scrolloff=3
		set backspace=indent,eol,start
		set matchpairs+=<:> " use % to jump between pairs
		runtime! macros/matchit.vim

		" Move up/down editor lines
		nnoremap j gj
		nnoremap k gk

		" Allow hidden buffers
		set hidden

		" Rendering
		set ttyfast

		" Status bar
		set laststatus=2

		" Last line
		set showmode
		set showcmd

		" Searching
		nnoremap / /\v
		vnoremap / /\v
		set hlsearch
		set incsearch
		set ignorecase
		set smartcase
		set showmatch
		map <leader><space> :let @/=''<cr> " clear search

		" Remap help key.
		inoremap <F1> <ESC>:set invfullscreen<CR>a
		nnoremap <F1> :set invfullscreen<CR>
		vnoremap <F1> :set invfullscreen<CR>

		" Textmate holdouts

		" Formatting
		map <leader>q gqip

		" Visualize tabs and newlines
		set listchars=tab:▸\ ,eol:¬
		" Uncomment this to enable by default:
		" set list " To enable by default
		" Or use your leader key + l to toggle on/off
		map <leader>l :set list!<CR> " Toggle tabs and EOL

		" Color scheme (terminal)
		set t_Co=256
		set background=dark
		let g:solarized_termcolors=256
		let g:solarized_termtrans=1
		" put https://raw.github.com/altercation/vim-colors-solarized/master/colors/solarized.vim
		" in ~/.vim/colors/ and uncomment:
		" colorscheme solarized

		" END_SHELLRC
		EOF
	[ ! -f "$CONFIGFILE" ] && touch "$CONFIGFILE"
	_append_section_in_file "$CONFIG" "$CONFIGFILE"
	_update_section_in_file "$CONFIG" "$CONFIGFILE"
	unset CONFIG CONFIGFILE VIM_HOME
}

configure_readline() {
	# https://www.gnu.org/software/bash/manual/html_node/Readline-Init-File-Syntax.html
	maybe_echo "configure_readline()"
	CONFIGFILE=$HOME/.inputrc
	{ CONFIG=$(cat) ; } <<-'EOF'
		# BEGIN_SHELLRC
		# Use the text that has already been typed as the prefix for searching through
		# commands (i.e. more intelligent Up/Down behavior)
		"\e[A": history-search-backward
		"\e[B": history-search-forward
		"\eOA": history-search-backward
		"\eOB": history-search-forward

		# Use Alt/Meta + Delete to delete the preceding word
		"\e[3;3~": kill-word

		$if Bash
		# E.g. typing !!<space> will replace the !! with your last command
		Space: magic-space
		$endif

		# Make Tab autocomplete regardless of filename case
		set completion-ignore-case on

		# List all matches in case multiple possible completions are possible
		set show-all-if-ambiguous on

		# Immediately add a trailing slash when autocompleting symlinks to directories
		set mark-symlinked-directories on

		# Do not autocomplete hidden files unless the pattern explicitly begins with a dot
		set match-hidden-files off

		# Show all autocomplete results at once
		set page-completions off

		# If there are more than 200 possible completions for a word, ask to show them all
		set completion-query-items 200

		# Show extra file information when completing, like `ls -F` does
		set visible-stats on

		# Be more intelligent when autocompleting by also looking at the text after
		# the cursor. For example, when the current line is "cd ~/src/mozil", and
		# the cursor is on the "z", pressing Tab will not autocomplete it to "cd
		# ~/src/mozillail", but to "cd ~/src/mozilla". (This is supported by the
		# Readline used by Bash 4.)
		set skip-completed-text on

		# Allow UTF-8 input and output, instead of showing stuff like $'\0123\0456'
		set input-meta on
		set output-meta on
		set convert-meta off

		# Treat hyphens and underscores as equivalent
		set completion-map-case on
		# END_SHELLRC
		EOF
	[ ! -f "$CONFIGFILE" ] && touch "$CONFIGFILE"
	_prepend_section_in_file "$CONFIG" "$CONFIGFILE"
	_update_section_in_file "$CONFIG" "$CONFIGFILE"
	if is_bash; then
		bind -f "$CONFIGFILE"
	fi
	unset CONFIG CONFIGFILE
}

configure_npm() {
	maybe_echo "configure_npm()"
	command -v npm > /dev/null || return 1
	if [ -z "$XDG_CONFIG_HOME" ]; then
		CONFIGFILE=~/.npmrc
	else
		mkdir -p "$XDG_CONFIG_HOME/npm"
		CONFIGFILE="$XDG_CONFIG_HOME/npm/npmrc"
	fi
	if [ -z "$XDG_CACHE_HOME" ]; then
		CACHEDIR=~/.npm
	else
		# mkdir -p "$XDG_CACHE_HOME/npm"
		CACHEDIR="$XDG_CACHE_HOME/npm"
	fi
	{ CONFIG=$(cat) ; } <<-EOF
		; BEGIN_SHELLRC
		userconfig="$CONFIGFILE"
		cache="$CACHEDIR"
		save-exact=true
		prefer-offline=true
		update-notifier=false
		omit=optional
		fund=false
		long=true
		; END_SHELLRC
		EOF
	export NPM_CONFIG_USERCONFIG="$CONFIGFILE"
	[ ! -f "$CONFIGFILE" ] && touch "$CONFIGFILE"
	_prepend_section_in_file "$CONFIG" "$CONFIGFILE"
	_update_section_in_file "$CONFIG" "$CONFIGFILE"
	unset CONFIG CONFIGFILE CACHEDIR
}

configure_git() {
	maybe_echo "configure_git()"
	command -v git > /dev/null || return 1
	CONFIGFILE=~/.gitconfig
	{ CONFIG=$(cat) ; } <<-EOF
		; BEGIN_SHELLRC

		[core]

		excludesfile = ~/.gitignore
		attributesfile = ~/.gitattributes
		# Treat spaces before tabs, lines that are indented with 8 or more spaces, and all kinds of trailing whitespace as an error
		whitespace = space-before-tab,trailing-space
		editor = nano
		quotepath = false
		# Autosave & Versions on OSX screw around with rebase workflow
		# http://www.git-tower.com/blog/make-git-rebase-safe-on-osx/
		trustctime = false
		autocrlf = false
		# safecrlf = true

		[color]

		# Use colors in Git commands that are capable of colored output when outputting to the terminal
		ui = auto

		[merge]

		# Include summaries of merged commits in newly created merge commit messages
		log = true

		[push]

		default = simple

		[credential]

		helper = cache --timeout=3600

		[alias]

		# View the SHA, description, and history graph of the latest 20 commits
		l = log --pretty=oneline -n 20 --graph
		# View the current working tree status using the short format
		s = status -s
		# Show the diff between the latest commit and the current state
		d = !"git diff-index --quiet HEAD -- || clear; git diff --patch-with-stat"
		# git di \$number shows the diff between the state \$number revisions ago and the current state
		di = !"d() { git diff --patch-with-stat HEAD~$1; }; git diff-index --quiet HEAD -- || clear; d"
		# Pull in remote changes for the current repository and all its submodules
		pullall = !"git pull; git submodule foreach git pull origin master"
		cloneall = clone --recursive
		# Commit all changes
		ca = !git add -A && git commit -av
		# Switch to a branch, creating it if necessary
		go = checkout -B
		# Show verbose output about tags, branches or remotes
		tags = tag -l
		branches = branch -a
		remotes = remote -v
		# Credit an author on the latest commit
		credit = "!f() { git commit --amend --author \"\$1 <\$2>\" -C HEAD; }; f"
		# Interactive rebase with the given number of latest commits
		rebasen = "!r() { git rebase -i HEAD~\$1; }; r"
		undopush = push -f origin HEAD^:master

		; END_SHELLRC
		EOF
	[ ! -f "$CONFIGFILE" ] && touch "$CONFIGFILE"
	_prepend_section_in_file "$CONFIG" "$CONFIGFILE"
	_update_section_in_file "$CONFIG" "$CONFIGFILE"
	CONFIGFILE=~/.gitignore
	{ CONFIG=$(cat) ; } <<-EOF
		# BEGIN_SHELLRC

		# OS generated files #
		######################
		.DS_Store
		.DS_Store?
		._*
		.Spotlight-V100
		.Trashes
		ehthumbs.db
		Thumbs.db

		# END_SHELLRC
		EOF
	[ ! -f "$CONFIGFILE" ] && touch "$CONFIGFILE"
	_prepend_section_in_file "$CONFIG" "$CONFIGFILE"
	_update_section_in_file "$CONFIG" "$CONFIGFILE"
	CONFIGFILE=~/.gitattributes
	{ CONFIG=$(cat) ; } <<-EOF
		# BEGIN_SHELLRC

		Package Control.sublime-settings -text

		# END_SHELLRC
		EOF
	[ ! -f "$CONFIGFILE" ] && touch "$CONFIGFILE"
	_prepend_section_in_file "$CONFIG" "$CONFIGFILE"
	_update_section_in_file "$CONFIG" "$CONFIGFILE"
	unset CONFIG CONFIGFILE
}

configure_wget() {
	command -v wget > /dev/null || return 1
	if [ -z "$XDG_CONFIG_HOME" ]; then
		CONFIGFILE=~/.wgetrc
		HSTSFILE=~/.wget-hsts
	else
		mkdir -p "$XDG_CONFIG_HOME/wget"
		CONFIGFILE=$XDG_CONFIG_HOME/wget/wgetrc
		HSTSFILE=$XDG_CONFIG_HOME/wget/wget-hsts
	fi
	maybe_local_encoding() {
		if wget --help | grep -q "local-encoding"; then
		    printf "local_encoding = UTF-8"
		fi
	}
	if wget --help | grep -q "hsts"; then
		alias wget="wget --config '$CONFIGFILE' --hsts-file '$HSTSFILE'"
	fi
	{ CONFIG=$(cat) ; } <<-EOF
		# BEGIN_SHELLRC

		# https://www.gnu.org/software/wget/manual/html_node/Wgetrc-Commands.html#Wgetrc-Commands
		timestamping = on
		no_parent = on
		timeout = 60
		tries = 3
		retry_connrefused = on
		trust_server_names = on
		follow_ftp = on
		adjust_extension = on
		# http://unix.stackexchange.com/q/34730/6040
		$(maybe_local_encoding)
		robots = off
		server_response = on
		user_agent = Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)

		# END_SHELLRC
		EOF
	[ ! -f "$CONFIGFILE" ] && touch "$CONFIGFILE"
	_prepend_section_in_file "$CONFIG" "$CONFIGFILE"
	_update_section_in_file "$CONFIG" "$CONFIGFILE"
	unset CONFIG CONFIGFILE HSTSFILE
	unset -f maybe_local_encoding
}

configure_zshell_line_editor() {
	is_zsh || return 0
	maybe_echo "configure_zshell_line_editor()"
	bindkey "\e[A" history-search-backward
	bindkey "\e[B" history-search-forward
	bindkey "\eOA" history-search-backward
	bindkey "\eOB" history-search-forward
}

# shellcheck disable=SC2317
load_python_autovenv() {
	maybe_echo "load_python_autovenv()"
	# Modified from:
	#   https://github.com/RaytingSec/autovenv/blob/master/.py_autovenv
	venv_auto() {
		venv_new="$(_venv_find)"
		venv_old="$(_venv_curr)"
		if [ -z "$venv_new" ] && [ -n "$venv_old" ]; then
			echo "Deactivating $(_venv_name "$venv_old")..."
			deactivate
		elif [ -n "$venv_new" ] && [ "$venv_new" != "$venv_old" ]; then
			echo "Activating $(_venv_name "$venv_new")..."
			. "${venv_new}/bin/activate"
		fi
	}
	_venv_candidates() {
		echo "$1/.venv"
		echo "$1/.env"
	}
	_venv_find() {
		venv_root=.
		j=0
		while [ "$j" -le 5 ]; do
			venv_real="$(cd "$venv_root" && pwd -P)"
			for candidate in $( _venv_candidates "$venv_real" ) ; do
				if [ -f "$candidate/bin/activate" ]; then
					cd "$candidate" && pwd -P
					return
				fi
			done
			[ "$venv_real" = "/" ] && break
			venv_root="${venv_root}/.."
			j=$(( j + 1 ))
		done
		unset venv_root venv_real candidate
	}
	_venv_curr() {
		if [ -n "$VIRTUAL_ENV" ] && [ "$(type -t deactivate)" = 'function' ]; then
			echo "$VIRTUAL_ENV"
		fi
	}
	_venv_ps1() {
		if [ -z "$VIRTUAL_ENV" ]; then
			printf ""
		else
			printf "%s" "$(basename "$(dirname "$(_venv_curr)")")"
		fi
	}
	_venv_name() {
		printf "%s" "$(basename "$(dirname "$1")")"
	}
}

set_default_editor() {
	maybe_echo "set_default_editor()"
	if command -v nano > /dev/null; then
		export VISUAL="nano"
		export EDITOR="nano"
	fi
}

run_prompt_commands() {
	maybe_echo "run_prompt_commands()"
	# Make history available all sessions
	history -a
	venv_auto
}

set_path() {
	maybe_append() {
		if [ -d "$1" ]; then export PATH="$PATH":"$1"; fi
	}
	maybe_prepend() {
		if [ -d "$1" ]; then export PATH="$1":"$PATH"; fi
	}
	# Homebrew
	if command -v brew > /dev/null; then
		BREW_PREFIX=$(brew --prefix)
		maybe_prepend "$BREW_PREFIX/bin:$BREW_PREFIX/sbin"
		maybe_prepend "$BREW_PREFIX/opt/sqlite/bin"
		maybe_prepend "$BREW_PREFIX/opt/ffmpeg@5/bin"
		maybe_prepend "$BREW_PREFIX/opt/php@8.1/bin"
		maybe_prepend "$BREW_PREFIX/opt/php@8.1/sbin"
		maybe_prepend "$BREW_PREFIX/opt/python/libexec/bin"
		maybe_prepend "$BREW_PREFIX/opt/python@3.12/bin"
		maybe_prepend "$BREW_PREFIX/usr/local/opt/automysqlbackup/sbin"
		unset BREW_PREFIX
	fi
	# Mac apps
	maybe_prepend "/Applications/Sublime Text.app/Contents/SharedSupport/bin"
	maybe_prepend "/Applications/Tower.app/Contents/MacOS"
	maybe_prepend "/Applications/VMware Fusion.app/Contents/Library"
	maybe_prepend "/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
	maybe_prepend "/Applications"
	# Extra
	maybe_prepend "$HOME/.cargo/bin"
	maybe_prepend "$HOME/bin/automysqlbackup-v3.0_rc6"
	maybe_prepend "$HOME/.bun"
	# pipx
	maybe_prepend "$HOME/.local/bin"
	# Opalstack
	maybe_prepend "$HOME/local"
	if [ -d "$HOME/local" ]; then
		for D in "$HOME"/local/*/; do
			export PATH="$D:$PATH"
			maybe_prepend "$D/bin"
		done
	fi
	unset D
	unset -f maybe_prepend maybe_append
}

make_utility_functions() {
	maybe_echo "make_utility_functions()"
	wordpress_delete_thumbnails() {
		if [[ "$(pwd)" == *"/uploads"* ]]; then
			find . -regextype egrep -regex ".+-[0-9]+?x[0-9]+\.(jpe?g|png)$" -type f -print0 | xargs -0 rm
		fi
	}
	wordpress_delete_thumbnails() {
		if [[ "$(pwd)" == *"/uploads"* ]]; then
			find . -regextype egrep -regex ".+\.(jpe?g|png)$" -type f -print0 | xargs -0 mogrify -resize "3072x3072>" -quality 92
		fi
	}
}

# shellcheck disable=SC3010,SC3028,SC3030,SC3044,SC3054
load_bash_completion() {
	is_bash || return 0
	complete -cf sudo
	if ! [ "${BASH_VERSINFO:-0}" -ge 4 ]; then
		echo "... Bash version too old (${BASH_VERSION}); not loading completions"
		return 1
	fi
	type _get_comp_words_by_ref > /dev/null 2>&1 && return 0
	maybe_echo "load_bash_completion()"
	PATHS=(
		"$sysconfdir/profile.d/bash_completion.sh"
		"/usr/share/bash-completion/bash_completion"
		"/etc/bash_completion"
		"/sw/etc/bash_completion"
		"/usr/local/etc/bash_completion"
	)
	for P in "${PATHS[@]}"; do
		[ -f "$P" ] && maybe_echo "... $P"
		if [[ $PS1 && -f $P ]]; then
			unalias sudo > /dev/null 2>&1 # this alias clashes with bash-completion
			. "$P"
			break
		fi
	done
	unset P PATHS
}

load_zsh_completion() {
	# See: https://zsh.sourceforge.io/Doc/Release/Completion-System.html#index-matcher_002dlist_002c-completion-style
	is_zsh || return 0
	maybe_echo "load_zshell_completion()"
	autoload -Uz compinit && compinit
	zstyle ':completion:*' matcher-list 'r:|?=**'
	# autoload -U +X compinit && compinit
	# zstyle ':completion:*' matcher-list \
	# 	'm:{[:lower:]}={[:upper:]}' \
	# 	'+r:|[._-]=* r:|=*' \
	# 	'+l:|=*'
}

load_python_completions() {
	# for zsh: https://stackoverflow.com/a/75791863
	maybe_echo "load_python_completions()"
	command -v 'register-python-argcomplete' > /dev/null || return 1
	load_python_completion() {
		command -v "$1" > /dev/null && eval "$(register-python-argcomplete "$1")"
	}
	load_python_completion pipx
	unset -f load_python_completion
}

configure_ssh() {
	maybe_echo "configure_ssh()"
	CONFIGFILE=~/.ssh/config
	[ -f "$CONFIGFILE" ] || return 1
	{ CONFIG=$(cat) ; } <<-'EOF'
		# BEGIN_SHELLRC

		## SSH client settings for all hosts
		##

		ServerAliveInterval 30
		ServerAliveCountMax 120
		Compression yes
		UseRoaming no

		## Useful to auto-unlock keys macOS
		Host *
		    AddKeysToAgent yes
		    UseKeychain yes

		## Work
		##

		Host workers theworkers opalstack
		    HostName opal6.opalstack.com
		    User theworkers

		Host cuba_admin_nebula
		    # Requires Nebula connection
		    HostName 100.100.1.1
		    User theworkers
		    Port 451

		Host cuba_admin_lan
		    HostName cuba
		    User theworkers
		    Port 451

		Host nebula
		    HostName 135.181.203.23
		    User root

		Host gitea
		    # Used for interactive shells
		    HostName opal6.opalstack.com
		    User theworkers_gitea
		    IdentityFile ~/.ssh/id_ed25519_gitea
		    IdentitiesOnly yes

		Host code.theworkers.net
		    # Used by `git` commands
		    HostName code.theworkers.net
		    User theworkers_gitea
		    IdentityFile ~/.ssh/id_ed25519
		    IdentitiesOnly yes

		## Projects
		##

		Host blackburn
		    HostName studio-blackburn.opalstacked.com
		    User studio_blackburn

		Host thenewschool parsons
		    HostName thenewschool.opalstacked.com
		    User thenewschool
		    IdentityFile ~/.ssh/id_ed25519

		# END_SHELLRC
		EOF
	_append_section_in_file "$CONFIG" "$CONFIGFILE"
	_update_section_in_file "$CONFIG" "$CONFIGFILE"
	unset CONFIG CONFIGFILE
}

cleanup_macos() {
	is_darwin || return 0
	sudo -v
	# # Sparkle framework leftovers
	# find "$HOME" -maxdepth 10 -type d -name ".Sparkle"
	# # Lightroom media cache files
	# # https://news.ycombinator.com/item?id=11095581
	# rm "$HOME/Library/Caches/Adobe/Lightroom/Video/Media Cache Files/*"
	# rm "$HOME/Library/Application Support/Adobe/Common/Media Cache Files/*"
}

set_locale() {
	maybe_echo "set_locale()"
	# macOS only recognises "UTF-8", not "utf8"
	if ! locale -a | grep -ixq 'en_us.utf-\?8'; then
		echo "... UTF8 locale not ready."
		echo "... Please run:"
		echo "\$ sudo locale-gen \"en_US.UTF-8\""
		return 1
	fi
	export LC_ALL=en_US.UTF-8
	export LANG=en_US.UTF-8
}

set_prompt_command() {
	maybe_echo "set_prompt_command()"
	PROMPT_COMMAND="run_prompt_commands; $PROMPT_COMMAND"
}

# shellcheck disable=SC3001
main() {
	maybe_echo "main()"
	{ FUNCTIONS_1=$(cat) ; } <<-'EOF'
		setup_sh
		setup_bash
		setup_zsh
		set_locale
		set_bash_prompt_string
		set_zsh_prompt_string
		set_xdg_directories
		set_path
		configure_darwin
		configure_linux
		set_shell_options
		set_zsh_options
		set_bash_options
		set_ls_colors
		set_default_editor
		make_aliases
		configure_ssh
		configure_readline
		configure_zshell_line_editor
		configure_vim
		configure_nano
		configure_npm
		configure_git
		configure_wget
		load_bash_completion
		load_zsh_completion
		load_python_completions
		load_python_autovenv
		make_utility_functions
		set_prompt_command
		EOF
	# Run main functions
	while IFS= read -r line || [ -n "$line" ]; do
		$line
	done < <(printf '%s' "$FUNCTIONS_1")
	# Unset main functions
	while IFS= read -r line || [ -n "$line" ]; do
		unset -f "$line"
	done < <(printf '%s' "$FUNCTIONS_1")
	unset FUNCTIONS_1
	{ FUNCTIONS_2=$(cat) ; } <<-'EOF'
		_prepend_section_in_file
		_append_section_in_file
		_update_section_in_file
		is_darwin
		is_linux
		is_smart_terminal
		is_bash
		is_zsh
		EOF
	# Unset utility functions
	while IFS= read -r line || [ -n "$line" ]; do
		unset -f "$line"
	done < <(printf '%s' "$FUNCTIONS_2")
	unset FUNCTIONS_2
}

main
unset -f main

